import Head from 'next/head'
import Image from 'next/image'

import NavBar from './navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>CryptoCoin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='' style={{ background: '#11144c'}}>
        <NavBar />
        <section className='flex flex-wrap items-center justify-between px-20 pt-20'>
          <div className=''>
            <h1 className='text-3xl  xl:text-7xl lg:text-7xl leading-15 pt-12 text-white'>Your gateway<br /> to <span className="text-green-500">Bitcoin</span> & <br /> beyond</h1>
            <p className='text-white  leading-10'>The tools and information you need to buy,<br /> sell, trade, invest, and spend cryptocurrencies</p>
          </div>
          <Image src="/first.png" alt="" width={400} height={400} className="" />
        </section>
      </main>
    </>
  )
}
