import {useEffect, useState} from 'react';
import Link from 'next/link'
import Head from 'next/head'
import NavBar from './navbar'
import Footer from './footer'
import CardCoin from './cardcoin'
import axios from "axios";

export default function Coinpage() {
  const [coins, setCoins] = useState([]);
  const [search, setSearch] = useState("");

  const getData = async () => {
    try {
      const res = await axios.get(
        "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false"
      );
      setCoins(res.data);
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    getData()
  }, []);

  return (
    <>
      <Head>
        <title>CryptoCoin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-[100%]' style={{ background: '#11144c'}}>
        <NavBar />
          <section className="pt-24 flex justify-center">
            <div className="flex mb-10">
              <input type="text"
                className="border text-xs p-2 w-80 rounded-lg bg-blue-900 text-white "
                placeholder="Search a Coin..."
                autoFocus
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
          </section>
          <CardCoin coins={coins} search={search} />
        <Footer />
      </main>
    </>

  )

}
