import Head from 'next/head'
import NavBar from './navbar'
import Footer from './footer'
import Image from 'next/image'

export default function Coinpage() {
  return (
    <>
      <Head>
        <title>CryptoCoin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-blue-50">
        <div className="bg-blue-800 pb-16 relative">
          <NavBar />
        </div>
        <section className="pt-24 pb-10 flex flex-wrap justify-between px-20 gap-10">
          <div className="bg-blue-50 rounded-lg w-60 h-auto shadow-lg shadow-blue-200 transition ease-in-out delay-200 duration-400 hover:scale-105 hover:cursor-pointer">
            <Image src="/blogbit.jpg" alt=""  className="rounded-t-lg" width={250} height={220} />
            <h1 className="text-blue-600 text-sm p-2 underline">Bitcoin, Ethereum Technical Analysis: BTC Jumps to 6-Month High
                Above $24000 – Market Updates Bitcoin News</h1>
            <p className="text-xs text-gray-500 leading-5 p-2 text-justify">Bitcoin surged above $24000 on Feb. 02, as markets continued to react to the
              latest U.S. Federal Reserve policy decision.</p>
          </div>
          
          <div className="bg-blue-50 rounded-lg w-60 h-auto shadow-lg shadow-blue-200 transition ease-in-out delay-200 duration-400 hover:scale-105 hover:cursor-pointer">
            <Image src="/blogethe.jpg" alt=""  className="rounded-t-lg" width={250} height={220} />
            <h1 className="text-blue-600 text-sm p-2 underline">BEthereum Network Usage Skyrockets As ETH Hits Two-Month</h1>
            <p className="text-xs text-gray-500 leading-5 p-2 text-justify">As various metrics under the Ethereum network have continued to show a steady
              increase in the past few months Ethereum on-chain activity.</p>
          </div>
          
          <div className="bg-blue-50 rounded-lg w-60 h-auto shadow-lg shadow-blue-200 transition ease-in-out delay-200 duration-400 hover:scale-105 hover:cursor-pointer">
            <Image src="/blogcash.png" alt=""  className="rounded-t-lg" width={250} height={220} />
            <h1 className="text-blue-600 text-sm p-2 underline">Bitcoin, Ethereum Technical Analysis: BTC Jumps to 6-Month High
                Above $24000 – Market Updates Bitcoin News</h1>
            <p className="text-xs text-gray-500 leading-5 p-2 text-justify">Bitcoin surged above $24000 on Feb. 02, as markets continued to react to the
              latest U.S. Federal Reserve policy decision.</p>
          </div>
          
          <div className="bg-blue-50 rounded-lg w-60 h-auto shadow-lg shadow-blue-200 transition ease-in-out delay-200 duration-400 hover:scale-105 hover:cursor-pointer">
            <Image src="/blogusdt.webp" alt=""  className="rounded-t-lg" width={250} height={220} />
            <h1 className="text-blue-600 text-sm p-2 underline">Tether (USDT) becomes the leading stablecoin in the world’s emerging
                markets</h1>
            <p className="text-xs text-gray-500 leading-5 p-2 text-justify">It's official: Tether (USDT) is the leading stablecoin in emerging markets around the
              world,especially in Brazil and Argentina.</p>
          </div>
          
          <div className="bg-blue-50 rounded-lg w-60 h-auto shadow-lg shadow-blue-200 transition ease-in-out delay-200 duration-400 hover:scale-105 hover:cursor-pointer">
            <Image src="/blogdog.webp" alt=""  className="rounded-t-lg" width={250} height={220} />
            <h1 className="text-blue-600 text-sm p-2 underline">Rumor has it that Dogecoin could shift to proof-of-stake — What does
              that mean for miners?</h1>
            <p className="text-xs text-gray-500 leading-5 p-2 text-justify">Dogecoin shifting to proof-of-stake would be good for the environment, but what
              impact would it have on miners and ASIC manufacturers?</p>
          </div>
        </section>
        <Footer />
      </main>
    </>
    
  )
}